### ISSUE TITLE
The file system provider does not implement the IFileContentProvider interface.

### ISSUE THREAD

**Issue by isthaison** [DevExpress-Examples/how-to-connect-aspnetcore-file-manager-to-database#2]
````
 var config = new FileSystemConfiguration {
             ...
                AllowDownload = true,
                AllowUpload = true,
...
                AllowedFileExtensions = new string[0]
            };
````

**Comment by isthaison** [comment]
@CodeKarno  please check again

**Comment by CodeKarno** [comment]
@isthaison,

Thank you for your idea. This repository shows a simple example of the custom provider implementation. So, we don't demonstrate implementation of all file system interfaces there. However, we may add the IFileContentProvider functionality to the example in the future.

If you'd like to see a more detailed example of the custom provider, take a look at this demo: [Azure Server-Side Binding](https://demos.devexpress.com/ASPNetCore/Demo/FileManager/AzureServerBinding/). It shows the implementation of all file system interfaces.
